### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [lekoala/silverstripe-sparkpost#12]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0.

**Comment by lekoala** [comment]
there is no hard dependency on Emogrifier, and the api is the same, so this should not be an issue. Let me know if there is something else I can change.
