### ISSUE TITLE
Undefined index: transmission_id

### ISSUE THREAD

**Issue by martinduparc** [lekoala/silverstripe-sparkpost#2]
`transmission_id` isn't defined. This is where the issue is https://github.com/lekoala/silverstripe-sparkpost/blob/master/code/SparkPostAdmin.php#L267

Here is a var_dump of the $message object:

```
array(10) {
  ["customer_id"]=&gt;
  string(5) "-------"
  ["error_code"]=&gt;
  string(3) "501"
  ["event_id"]=&gt;
  string(17) "--------------"
  ["msg_from"]=&gt;
  string(21) "test@test.net"
  ["raw_reason"]=&gt;
  string(30) "501 5.5.2 RCPT TO syntax error"
  ["reason"]=&gt;
  string(30) "501 5.5.2 RCPT TO syntax error"
  ["remote_addr"]=&gt;
  string(20) "----------------"
  ["tdate"]=&gt;
  string(24) "2016-04-27T20:40:45.000Z"
  ["type"]=&gt;
  string(16) "policy_rejection"
  ["timestamp"]=&gt;
  string(29) "2016-04-27T16:40:45.000-04:00"
}

```

**Comment by lekoala** [comment]
mhh interesting ! I have to make a more flexible view for messages events to account for all kinds of events. I'll probably split the delivery part from the error part. I'll publish a quickfix to prevent this error from happening but I'll make it more robust in the near future.

**Comment by lekoala** [comment]
ok, fixed in commit https://github.com/lekoala/silverstripe-sparkpost/commit/eea372595d7fc5bc2fda4d2f1eeba44c4daec34e
