### ISSUE TITLE
Bug: Domain with more than 1 root

### ISSUE THREAD

**Issue by trev** [lekoala/silverstripe-sparkpost#3]
https://github.com/lekoala/silverstripe-sparkpost/blob/master/code/SparkPostAdmin.php#L610-L620 will parse something like: `www.domain.com.au` to `com.au`.

Probably a better idea to just allow the user to configure the sending domain in the config. I can make the changes if you want to go down that route.

**Comment by lekoala** [comment]
You can configure the sending domain through yml. The automated methods are just there to provide some sensible defaults (it either parse the admin emails or take the current domain name) if you don't specify anything. Did you try ?

https://github.com/lekoala/silverstripe-sparkpost/blob/master/_config/sparkpost.yml#L24-28

**Comment by trev** [comment]
Ahh! I hadn't seen that. Still, the method is inherently defective for anything but single top level domains. Might be worth just ditching it altogether.

**Comment by lekoala** [comment]
Well, I could simply remove the www and otherwise keep the subdomain, and in this case it would work when there are more than 1 root. But you are right, it's not perfect at the moment.

**Comment by lekoala** [comment]
i'm closing this issue for now. taking the default sender domain seems good enough for me. it's still configurable through yml.
